on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build WASM
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - run: git fetch
    - run: git checkout -t origin/build
    - run: git rebase master || (git rebase --abort && git reset --hard master)
    - run: make deps
    - run: make build
    - run: |
        git add docs
        if $(git diff --quiet --exit-code --cached); then
          echo 'No changes detected.'
        else
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am 'build: Build latest version'
          git push -f
        fi
