on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - run: |
        git checkout build
        git rebase master
        make build
        if $(git diff --quiet --exit-code --cached); then
          git commit -am 'build: Build latest version'
          git push origin build
        fi
